apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-cicd-deployment
  labels:
    app: node-cicd-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-cicd-deployment
  template:
    metadata:
      labels:
        app: node-cicd-deployment
    spec:
      containers:
        - name: c-node-cicd-deployment
          image: memarchi/fiap-k8s2-aula7:v1
          ports:
            - containerPort: 3000
